### ISSUE TITLE
segfault on partial application of certain dyads when followed by a semicolon

### ISSUE THREAD

**Issue by tangentstorm** [kevinlawler/kona#451]
The following code segfaults in c52e3f1e4e7 on linux.

```
f:{c:x;y}
g:f[;0]; h:f[;1]
```

It works fine if the second line is broken into two separate lines.

**Comment by tangentstorm** [comment]
I have a simpler test case that causes the problem:

    {c:y}[];

It seems to be the combination of:

- a partial application...
- of a dyadic function...
- that performs an assignment..
- followed by a semicolon

**Comment by tangentstorm** [comment]
stack trace at the point of error. almost looks like a parser issue...?
```
(gdb) where
#0  0x00000000004408a3 in dot_monadic (x=0x0) at src/vd.c:326
#1  0x00000000004281e3 in ex2 (v=0x7ffff7fe8d58, k=0x0) at src/kx.c:892
#2  0x0000000000427756 in ex1 (w=0x7ffff7fe8d58, k=0x0, i=0x7fffffffd008, n=2, f=1) at src/kx.c:829
#3  0x0000000000425989 in ex0 (v=0x7ffff7fe8d58, k=0x0, r=0) at src/kx.c:688
#4  0x000000000042569b in ex_ (a=0x7fffffffd0f8, r=0) at src/kx.c:664
#5  0x000000000042573b in ex (a=0x7ffff7fe9c00) at src/kx.c:672
#6  0x000000000041a8a1 in XN (s=0x46f97f "{c:y}[];", n=8) at src/k.c:54
#7  0x000000000041a821 in X (s=0x46f97f "{c:y}[];") at src/k.c:50
#8  0x000000000044a6d6 in tc (a=0x46e58f "_n", b=0x46f97f "{c:y}[];") at src/tests.c:40
#9  0x000000000044fd4e in tests02 () at src/tests.c:281
#10 0x000000000044a9d5 in test () at src/tests.c:70
#11 0x000000000041e1ef in kinit () at src/kc.c:160
#12 0x000000000044a4e1 in main (argc=1, argv=0x7fffffffe548) at src/main.c:6
```

**Comment by tavmem** [comment]
This was resolved by the pull request from tangentstorm
 c75007d7528c5e15578dc517b0d751e300a49493
