### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by tavmem** [kevinlawler/kona#489]
$ ./k_test
t:0
t:50
t:100
t:150
t:200
t:250
t:300
t:350
t:400
t:450
t:500
t:550
t:600
t:650
t:700
t:750
t:800
t:850
t:900
t:950
t:1000
t:1050
Test pass rate: 1.0000, Total: 1096, Passed: 1064, Skipped: 32, Failed: 0, Time: 0.392466s
OK
K Console - Enter \ for help

  \\

=================================================================
==11848==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f2f84bdd850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x45623f in alloc src/km.c:45
    #2 0x458ddc in newPDA src/km.c:318
    #3 0x418d7e in complete src/p.c:91
    #4 0x43b929 in line src/kc.c:271
    #5 0x43e0e9 in attend src/kc.c:439
    #6 0x48bb87 in main src/main.c:9
    #7 0x7f2f83fc5009 in __libc_start_main (/lib64/libc.so.6+0x21009)

SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
$

**Comment by tavmem** [comment]
This no longer occurs.
Closing this issue.
